### ISSUE TITLE
The documents present in database are not shown in UI.

### ISSUE THREAD

**Issue by Arslan-Mehmood1** [AI-Commandos/RAGMeUp#13]
![image](https://github.com/user-attachments/assets/8352761f-0510-4fe6-8128-5efafa19f475)

**Comment by ErikTromp** [comment]
Currently, the folder configured in the UI's application.conf must equal that of your Python server (default is both ./data).

I will rephrase this issue instead to make a proper coupling between the two.

**Comment by Arslan-Mehmood1** [comment]
Got it, currently, I've place data in root dir outside server dir.
and ran server using python server/server.py

**Comment by ErikTromp** [comment]
Closing in favor of #14
