### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by nickworks** [AI-Commandos/RAGMeUp#18]
What version of python and pip are we supposed to use? I'm using homebrew to manage python installations, which:

`python3 --version` yields `Python 3.12.4`
`python3.12 --version` yields `Python 3.12.4`
`python3.11 --version` yields `Python 3.11.9`
`python3.10 --version` yields `Python 3.10.14`

`pip --version` yields `pip 24.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`
`pip3 --version` yields `pip 24.2 from /opt/homebrew/lib/python3.12/site-packages/pip (python 3.12)`
`pip3.12 --version` yields `pip 24.2 from /opt/homebrew/lib/python3.12/site-packages/pip (python 3.12)`
`pip3.11 --version` yields `pip 24.1 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)`
`pip3.10 --version` yields `pip 24.0 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)`

`python3.12 server.py` yields:
```
Traceback (most recent call last):
  File "/Users/nick/projects/ai/RAGMeUp/server/server.py", line 1, in <module>
    from flask import Flask, request, jsonify, send_file
ModuleNotFoundError: No module named 'flask'
```

`python3.11 server.py` yields:
```
Traceback (most recent call last):
  File "/Users/nick/projects/ai/RAGMeUp/server/server.py", line 5, in <module>
    from RAGHelper_cloud import RAGHelperCloud
  File "/Users/nick/projects/ai/RAGMeUp/server/RAGHelper_cloud.py", line 4, in <module>
    from provenance import (compute_llm_provenance_cloud, compute_rerank_provenance, DocumentSimilarityAttribution)
  File "/Users/nick/projects/ai/RAGMeUp/server/provenance.py", line 5, in <module>
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'
```

`python3.10 server.py` yields:
```
Traceback (most recent call last):
  File "/Users/nick/projects/ai/RAGMeUp/server/server.py", line 1, in <module>
    from flask import Flask, request, jsonify, send_file
ModuleNotFoundError: No module named 'flask'
```

`pip3 install -r requirements` or
`pip3.12 install -r requirements` yield:

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.
    
    Read more about this behavior here: <https://peps.python.org/pep-0668/>
```

`pip install -r requirements` or
`pip3.11 install -r requirements` or
`pip3.10 install -r requirements` yield:
```
ERROR: Could not find a version that satisfies the requirement bitsandbytes==0.43.1 (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)
ERROR: No matching distribution found for bitsandbytes==0.43.1
```

If I enable a virtual environment (with `source venv/bin/activate`) the venv becomes active. Running ANY of the `pip install` commands from above yield the following when the venv is active:

```
ERROR: Could not find a version that satisfies the requirement bitsandbytes==0.43.1 (from versions: 0.31.8, 0.32.0, 0.32.1, 0.32.2, 0.32.3, 0.33.0, 0.33.1, 0.34.0, 0.35.0, 0.35.1, 0.35.2, 0.35.3, 0.35.4, 0.36.0, 0.36.0.post1, 0.36.0.post2, 0.37.0, 0.37.1, 0.37.2, 0.38.0, 0.38.0.post1, 0.38.0.post2, 0.38.1, 0.39.0, 0.39.1, 0.40.0, 0.40.0.post1, 0.40.0.post2, 0.40.0.post3, 0.40.0.post4, 0.40.1, 0.40.1.post1, 0.40.2, 0.41.0, 0.41.1, 0.41.2, 0.41.2.post1, 0.41.2.post2, 0.41.3, 0.41.3.post1, 0.41.3.post2, 0.42.0)
ERROR: No matching distribution found for bitsandbytes==0.43.1
```

At this point I've been using Python for years. But it almost never, ever, ever, ever works. The package management / virtual environments simply do not work. What am I doing wrong? Thanks!

**Comment by ErikTromp** [comment]
Weird... shouldn't be this hard. But to get you going:

- I am on Python 3.11.5
- Flask has never worked for me ever through requirements.txt, just run `pip install flask` separately
- sentence-transformers and bitsandbytes work well on Linux/WSL and even Windows but are knowingly painful when you are on Mac. https://huggingface.co/docs/bitsandbytes/main/en/installation even suggests there simply is no Mac support...

**Comment by nickworks** [comment]
Thank you for the response! That makes sense.

**Comment by ErikTromp** [comment]
Depending on how you want to use RAG Me Up, you could just comment out bitsandbytes and the quantization code as that is all we use it for.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
