### ISSUE TITLE
psycopg2.errors.InvalidSchemaName: schema "idx_sparse_vectors_bm25" does not exist

### ISSUE THREAD

**Issue by Havlight** [AI-Commandos/RAGMeUp#25]
I followed the instructions, Using Postgres (advised for production) in wsl2 and Ubuntu 24.04, and then ran server.py.
so far there was no problem, but after I chatted with the server I got psycopg2.errors.InvalidSchemaName: schema "idx_sparse_vectors_bm25" does not exist.
I solved this by simply creating the schema using CALL paradedb.create_bm25(
        index_name => 'idx_sparse_vectors_bm25',
        table_name => 'sparse_vectors',
        key_field => 'id',
        text_fields => paradedb.field('content') || paradedb.field('metadata')
);
Because I am a beginner, I wonder whether I did something wrong or the code has a problem.

**Comment by ErikTromp** [comment]
No it's probably not you haha, ParadeDB uses a lot of default names that mess things and we may have gotten things backward. Can you show me what your database structure looks like? You can use a tool like DBeaver to connect when your Docker is running to see what databases and schemas are there.

**Comment by Havlight** [comment]
![image](https://github.com/user-attachments/assets/ac39ece4-30bb-405b-8d3f-5fd4fbd965a3)
is it enough?

**Comment by ErikTromp** [comment]
You created the schema manually now, right? It should be made when the index is created. I will see if I can reproduce this.

**Comment by Havlight** [comment]
Yes, I created idx_sparse_vectors_bm25 by myself in psql.
I saw an SQL that creates the schema in a function,setup_database() of PostgresBM25Retriever.py, but it doesn't seem to execute correctly.
Also, this is my first time using PostgreSQL, so I can't find the reason.

**Comment by ErikTromp** [comment]
Yeah for now you can just manually run that code which creates the schema and indexes and you should be fine

**Comment by Havlight** [comment]
I rebuilt the docker, and changed line 42 in PostgresBM25Retriever.py from "IF NOT EXISTS" to "IF EXISTS", and then it will create idx_sparse_vectors_bm25 automatically when initializing the server.

**Comment by ErikTromp** [comment]
That makes sense. Can you make a PR for this too?

**Comment by Havlight** [comment]
OK!
